# Generated by Django 6.1.1 on 2026-09-24 15:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('period_number', models.PositiveSmallIntegerField(default=1)),
                ('session_type', models.CharField(choices=[('REGULAR', 'Regular Lecture'), ('LAB', 'Laboratory Session'), ('TUTORIAL', 'Tutorial'), ('REMEDIAL', 'Remedial / Extra Class')], default='REGULAR', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('LOCKED', 'Locked')], default='SUBMITTED', max_length=20)),
                ('topic_covered', models.TextField(blank=True, default='')),
                ('is_locked', models.BooleanField(default=False, help_text='Locks after 24 hours or administrative cutoff to enforce audit rules')),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faculty', models.ForeignKey(help_text='Instructor who conducted and marked the attendance', on_delete=django.db.models.deletion.PROTECT, related_name='conducted_sessions', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_sessions', to='academic.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_sessions', to='academic.subject')),
                ('timetable_slot', models.ForeignKey(blank=True, help_text='Optional link to recurring weekly timetable schedule', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_sessions', to='academic.timetableslot')),
            ],
            options={
                'ordering': ['-session_date', '-period_number'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late Arrival'), ('ON_DUTY', 'On Duty (Authorized)'), ('MEDICAL_LEAVE', 'Medical Leave (Authorized)')], db_index=True, default='PRESENT', max_length=20)),
                ('remarks', models.CharField(blank=True, default='', max_length=255)),
                ('marked_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='academic.student')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='attendance.attendancesession')),
            ],
            options={
                'ordering': ['student__roll_number'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late Arrival'), ('ON_DUTY', 'On Duty (Authorized)'), ('MEDICAL_LEAVE', 'Medical Leave (Authorized)')], max_length=20)),
                ('requested_status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late Arrival'), ('ON_DUTY', 'On Duty (Authorized)'), ('MEDICAL_LEAVE', 'Medical Leave (Authorized)')], max_length=20)),
                ('reason', models.TextField(help_text='Detailed justification (e.g. Sports tournament, Dengue fever hospitalization)')),
                ('document_url', models.CharField(blank=True, default='', help_text='Evidence URL or simulated certificate attachment path', max_length=500)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved & Reconciled'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20)),
                ('review_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_corrections', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_corrections', to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='attendance.attendancerecord')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='attendance__status_430648_idx')],
            },
        ),
        migrations.CreateModel(
            name='AttendanceAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('SESSION_CREATED', 'Initial Attendance Recorded'), ('SESSION_EDITED', 'Teacher In-Window Edit'), ('CORRECTION_APPROVED', 'Correction Workflow Approved'), ('ADMIN_OVERRIDE', 'Administrative Policy Override')], max_length=30)),
                ('previous_status', models.CharField(blank=True, default='', max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('reason', models.TextField(blank=True, default='')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_audit_entries', to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='attendance.attendancerecord')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['record', 'timestamp'], name='attendance__record__c80d1e_idx'), models.Index(fields=['changed_by', 'timestamp'], name='attendance__changed_a3f1f5_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['section', 'session_date'], name='attendance__section_5ac3d0_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['subject', 'session_date'], name='attendance__subject_aea6df_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['faculty', 'session_date'], name='attendance__faculty_b97ce5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancesession',
            unique_together={('section', 'subject', 'session_date', 'period_number')},
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['student', 'status'], name='attendance__student_fb4d40_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['session', 'status'], name='attendance__session_8dae34_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together={('session', 'student')},
        ),
    ]
