# Generated by Django 6.1.1 on 2026-09-24 18:00

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(default='Edumerge Institute of Technology', max_length=150)),
                ('default_threshold', models.DecimalField(decimal_places=2, default=Decimal('75.00'), help_text='Standard statutory minimum percentage for exam eligibility (default 75.00%)', max_digits=5)),
                ('condonation_threshold', models.DecimalField(decimal_places=2, default=Decimal('65.00'), help_text='Minimum threshold required for condonation consideration (default 65.00%)', max_digits=5)),
                ('warning_buffer_pct', models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Buffer percentage above threshold to trigger proactive warnings (e.g. 75-80%)', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_attendance_policies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Attendance Policies',
                'ordering': ['-is_active', '-updated_at'],
            },
        ),
    ]
