# Generated by Django 6.1.1 on 2026-09-24 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendancepolicy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceauditlog',
            name='action',
            field=models.CharField(choices=[('SESSION_CREATED', 'Initial Attendance Recorded'), ('SESSION_EDITED', 'Teacher In-Window Edit'), ('CORRECTION_APPROVED', 'Correction Workflow Approved'), ('CORRECTION_REJECTED', 'Correction Workflow Rejected'), ('ADMIN_OVERRIDE', 'Administrative Policy Override')], max_length=30),
        ),
    ]
