# Generated by Django 6.1.1 on 2026-09-24 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_label', models.CharField(help_text='e.g. 2026-2027', max_length=20, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g. CSE, ECE, MECH', max_length=10, unique=True)),
                ('name', models.CharField(help_text='Full department title', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='FacultyAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g. BTECH-CSE', max_length=20, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('total_semesters', models.PositiveSmallIntegerField(default=8)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.PositiveSmallIntegerField(help_text='1 to 8')),
                ('name', models.CharField(help_text='Section letter e.g. A, B, C', max_length=10)),
            ],
            options={
                'ordering': ['program', 'semester', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('registration_number', models.CharField(db_index=True, max_length=30, unique=True)),
                ('current_semester', models.PositiveSmallIntegerField(default=1)),
                ('admission_date', models.DateField(help_text='Crucial for calculating attendance denominator for lateral/late entrants')),
                ('guardian_name', models.CharField(blank=True, default='', max_length=100)),
                ('guardian_phone', models.CharField(blank=True, default='', max_length=20)),
            ],
            options={
                'ordering': ['roll_number'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g. CS401', max_length=20, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('credits', models.PositiveSmallIntegerField(default=3)),
                ('semester', models.PositiveSmallIntegerField(default=1)),
                ('min_attendance_pct', models.FloatField(default=75.0, help_text='Statutory threshold required to sit for semester examinations')),
                ('condonation_min_pct', models.FloatField(default=65.0, help_text='Lower floor eligible for condonation with approved medical/on-duty proof')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='TimetableSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')])),
                ('period_number', models.PositiveSmallIntegerField(help_text='1 (e.g. 9:00-9:50) through 7')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('room_number', models.CharField(default='CR-101', max_length=30)),
            ],
            options={
                'ordering': ['day_of_week', 'period_number'],
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('designation', models.CharField(default='Assistant Professor', max_length=60)),
                ('qualification', models.CharField(blank=True, default='M.Tech', max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faculty_members', to='academic.department')),
            ],
            options={
                'ordering': ['employee_id'],
            },
        ),
    ]
