# Generated by Django 6.1.1 on 2026-09-24 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facultyallocation',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='academic.academicyear'),
        ),
        migrations.AddField(
            model_name='facultyallocation',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='academic.faculty'),
        ),
        migrations.AddField(
            model_name='program',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='academic.department'),
        ),
        migrations.AddField(
            model_name='section',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='academic.academicyear'),
        ),
        migrations.AddField(
            model_name='section',
            name='mentor',
            field=models.ForeignKey(blank=True, help_text='Faculty member acting as the section mentor / class advisor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentored_sections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='section',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='academic.program'),
        ),
        migrations.AddField(
            model_name='facultyallocation',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='academic.section'),
        ),
        migrations.AddField(
            model_name='student',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academic.section'),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subject',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='academic.department'),
        ),
        migrations.AddField(
            model_name='facultyallocation',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='academic.subject'),
        ),
        migrations.AddField(
            model_name='timetableslot',
            name='allocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='academic.facultyallocation'),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('program', 'academic_year', 'semester', 'name')},
        ),
        migrations.AddIndex(
            model_name='facultyallocation',
            index=models.Index(fields=['faculty', 'is_active'], name='academic_fa_faculty_55d999_idx'),
        ),
        migrations.AddIndex(
            model_name='facultyallocation',
            index=models.Index(fields=['section', 'subject'], name='academic_fa_section_013db4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='facultyallocation',
            unique_together={('faculty', 'subject', 'section', 'academic_year')},
        ),
        migrations.AddIndex(
            model_name='timetableslot',
            index=models.Index(fields=['day_of_week', 'period_number'], name='academic_ti_day_of__d570bb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='timetableslot',
            unique_together={('allocation', 'day_of_week', 'period_number')},
        ),
    ]
