# Generated by Django 6.1.1 on 2026-09-24 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faculty',
            options={'ordering': ['employee_id'], 'verbose_name_plural': 'Faculty'},
        ),
        migrations.AddField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='section',
            name='max_capacity',
            field=models.PositiveSmallIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='subject',
            name='is_elective',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subject',
            name='program',
            field=models.ForeignKey(blank=True, help_text='Specific degree curriculum this subject is designed for', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='academic.program'),
        ),
        migrations.CreateModel(
            name='AcademicClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.PositiveSmallIntegerField(help_text='1 to 8')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_classes', to='academic.academicyear')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_classes', to='academic.program')),
            ],
            options={
                'verbose_name_plural': 'Academic Classes',
                'ordering': ['program', 'semester'],
                'unique_together': {('program', 'academic_year', 'semester')},
            },
        ),
        migrations.AddField(
            model_name='section',
            name='academic_class',
            field=models.ForeignKey(blank=True, help_text='Optional link to parent class cohort', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='academic.academicclass'),
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to='academic.academicyear')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to='academic.section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to='academic.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_enrollments', to='academic.subject')),
            ],
            options={
                'indexes': [models.Index(fields=['student', 'academic_year'], name='academic_co_student_481ee7_idx'), models.Index(fields=['section', 'subject'], name='academic_co_section_0358b0_idx')],
                'unique_together': {('student', 'subject', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_number', models.PositiveSmallIntegerField(help_text='1 to 8')),
                ('term', models.CharField(choices=[('ODD', 'Odd Semester (Fall)'), ('EVEN', 'Even Semester (Spring)')], default='EVEN', max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='academic.academicyear')),
            ],
            options={
                'ordering': ['academic_year', 'semester_number'],
                'unique_together': {('academic_year', 'semester_number')},
            },
        ),
    ]
